<BottomNav>:
    adaptive_height: True
    spacing: 5
    padding: 5

    MDIconButton:
        icon: 'home'

    MDIconButton:
        icon: 'magnify'

    MDIconButton:
        icon: 'movie'

    MDIconButton:
        icon: 'heart-outline'

    FitImage:
        source: root.avatar
        size_hint: None, None
        size: 80, 80
        radius: [80, ]
        pos_hint: {"center_x": 0.5, "center_y":6}